New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAA.smi -OutFile AA/AAAA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAB.smi -OutFile AA/AAAB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAC.smi -OutFile AA/AAAC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAD.smi -OutFile AA/AAAD.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABA.smi -OutFile AA/AABA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABB.smi -OutFile AA/AABB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABC.smi -OutFile AA/AABC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABD.smi -OutFile AA/AABD.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACA.smi -OutFile AA/AACA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACB.smi -OutFile AA/AACB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACC.smi -OutFile AA/AACC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACD.smi -OutFile AA/AACD.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAEA.smi -OutFile AA/AAEA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAEB.smi -OutFile AA/AAEB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAEC.smi -OutFile AA/AAEC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAED.smi -OutFile AA/AAED.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAA.smi -OutFile AB/ABAA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAB.smi -OutFile AB/ABAB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAC.smi -OutFile AB/ABAC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAD.smi -OutFile AB/ABAD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBA.smi -OutFile AB/ABBA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBB.smi -OutFile AB/ABBB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBC.smi -OutFile AB/ABBC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBD.smi -OutFile AB/ABBD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCA.smi -OutFile AB/ABCA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCB.smi -OutFile AB/ABCB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCC.smi -OutFile AB/ABCC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCD.smi -OutFile AB/ABCD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABEA.smi -OutFile AB/ABEA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABEB.smi -OutFile AB/ABEB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABEC.smi -OutFile AB/ABEC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABED.smi -OutFile AB/ABED.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAA.smi -OutFile AC/ACAA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAB.smi -OutFile AC/ACAB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAC.smi -OutFile AC/ACAC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAD.smi -OutFile AC/ACAD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBA.smi -OutFile AC/ACBA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBB.smi -OutFile AC/ACBB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBC.smi -OutFile AC/ACBC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBD.smi -OutFile AC/ACBD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCA.smi -OutFile AC/ACCA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCB.smi -OutFile AC/ACCB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCC.smi -OutFile AC/ACCC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCD.smi -OutFile AC/ACCD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACEA.smi -OutFile AC/ACEA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACEB.smi -OutFile AC/ACEB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACEC.smi -OutFile AC/ACEC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACED.smi -OutFile AC/ACED.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAA.smi -OutFile AD/ADAA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAB.smi -OutFile AD/ADAB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAC.smi -OutFile AD/ADAC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAD.smi -OutFile AD/ADAD.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAAA.smi -OutFile BA/BAAA.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAAB.smi -OutFile BA/BAAB.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAAC.smi -OutFile BA/BAAC.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAAD.smi -OutFile BA/BAAD.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BABA.smi -OutFile BA/BABA.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BABB.smi -OutFile BA/BABB.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BABC.smi -OutFile BA/BABC.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BABD.smi -OutFile BA/BABD.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BACA.smi -OutFile BA/BACA.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BACB.smi -OutFile BA/BACB.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BACC.smi -OutFile BA/BACC.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BACD.smi -OutFile BA/BACD.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAEA.smi -OutFile BA/BAEA.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAEB.smi -OutFile BA/BAEB.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAEC.smi -OutFile BA/BAEC.smi
New-Item -path BA -type directory; Invoke-WebRequest http://files.docking.org/2D/BA/BAED.smi -OutFile BA/BAED.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBAA.smi -OutFile BB/BBAA.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBAB.smi -OutFile BB/BBAB.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBAC.smi -OutFile BB/BBAC.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBAD.smi -OutFile BB/BBAD.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBBA.smi -OutFile BB/BBBA.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBBB.smi -OutFile BB/BBBB.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBBC.smi -OutFile BB/BBBC.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBBD.smi -OutFile BB/BBBD.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBCA.smi -OutFile BB/BBCA.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBCB.smi -OutFile BB/BBCB.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBCC.smi -OutFile BB/BBCC.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBCD.smi -OutFile BB/BBCD.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBEA.smi -OutFile BB/BBEA.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBEB.smi -OutFile BB/BBEB.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBEC.smi -OutFile BB/BBEC.smi
New-Item -path BB -type directory; Invoke-WebRequest http://files.docking.org/2D/BB/BBED.smi -OutFile BB/BBED.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCAA.smi -OutFile BC/BCAA.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCAB.smi -OutFile BC/BCAB.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCAC.smi -OutFile BC/BCAC.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCAD.smi -OutFile BC/BCAD.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCBA.smi -OutFile BC/BCBA.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCBB.smi -OutFile BC/BCBB.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCBC.smi -OutFile BC/BCBC.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCBD.smi -OutFile BC/BCBD.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCCA.smi -OutFile BC/BCCA.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCCB.smi -OutFile BC/BCCB.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCCC.smi -OutFile BC/BCCC.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCCD.smi -OutFile BC/BCCD.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCEA.smi -OutFile BC/BCEA.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCEB.smi -OutFile BC/BCEB.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCEC.smi -OutFile BC/BCEC.smi
New-Item -path BC -type directory; Invoke-WebRequest http://files.docking.org/2D/BC/BCED.smi -OutFile BC/BCED.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBA.smi -OutFile AD/ADBA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBB.smi -OutFile AD/ADBB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBC.smi -OutFile AD/ADBC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBD.smi -OutFile AD/ADBD.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCA.smi -OutFile AD/ADCA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCB.smi -OutFile AD/ADCB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCC.smi -OutFile AD/ADCC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCD.smi -OutFile AD/ADCD.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADEA.smi -OutFile AD/ADEA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADEB.smi -OutFile AD/ADEB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADEC.smi -OutFile AD/ADEC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADED.smi -OutFile AD/ADED.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAA.smi -OutFile AE/AEAA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAB.smi -OutFile AE/AEAB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAC.smi -OutFile AE/AEAC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAD.smi -OutFile AE/AEAD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBA.smi -OutFile AE/AEBA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBB.smi -OutFile AE/AEBB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBC.smi -OutFile AE/AEBC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBD.smi -OutFile AE/AEBD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECA.smi -OutFile AE/AECA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECB.smi -OutFile AE/AECB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECC.smi -OutFile AE/AECC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECD.smi -OutFile AE/AECD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEEA.smi -OutFile AE/AEEA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEEB.smi -OutFile AE/AEEB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEEC.smi -OutFile AE/AEEC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEED.smi -OutFile AE/AEED.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAA.smi -OutFile AF/AFAA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAB.smi -OutFile AF/AFAB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAC.smi -OutFile AF/AFAC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAD.smi -OutFile AF/AFAD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBA.smi -OutFile AF/AFBA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBB.smi -OutFile AF/AFBB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBC.smi -OutFile AF/AFBC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBD.smi -OutFile AF/AFBD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCA.smi -OutFile AF/AFCA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCB.smi -OutFile AF/AFCB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCC.smi -OutFile AF/AFCC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCD.smi -OutFile AF/AFCD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFEA.smi -OutFile AF/AFEA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFEB.smi -OutFile AF/AFEB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFEC.smi -OutFile AF/AFEC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFED.smi -OutFile AF/AFED.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAA.smi -OutFile AG/AGAA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAB.smi -OutFile AG/AGAB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAC.smi -OutFile AG/AGAC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAD.smi -OutFile AG/AGAD.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBA.smi -OutFile AG/AGBA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBB.smi -OutFile AG/AGBB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBC.smi -OutFile AG/AGBC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBD.smi -OutFile AG/AGBD.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDAA.smi -OutFile BD/BDAA.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDAB.smi -OutFile BD/BDAB.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDAC.smi -OutFile BD/BDAC.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDAD.smi -OutFile BD/BDAD.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDBA.smi -OutFile BD/BDBA.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDBB.smi -OutFile BD/BDBB.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDBC.smi -OutFile BD/BDBC.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDBD.smi -OutFile BD/BDBD.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDCA.smi -OutFile BD/BDCA.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDCB.smi -OutFile BD/BDCB.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDCC.smi -OutFile BD/BDCC.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDCD.smi -OutFile BD/BDCD.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDEA.smi -OutFile BD/BDEA.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDEB.smi -OutFile BD/BDEB.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDEC.smi -OutFile BD/BDEC.smi
New-Item -path BD -type directory; Invoke-WebRequest http://files.docking.org/2D/BD/BDED.smi -OutFile BD/BDED.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEAA.smi -OutFile BE/BEAA.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEAB.smi -OutFile BE/BEAB.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEAC.smi -OutFile BE/BEAC.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEAD.smi -OutFile BE/BEAD.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEBA.smi -OutFile BE/BEBA.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEBB.smi -OutFile BE/BEBB.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEBC.smi -OutFile BE/BEBC.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEBD.smi -OutFile BE/BEBD.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BECA.smi -OutFile BE/BECA.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BECB.smi -OutFile BE/BECB.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BECC.smi -OutFile BE/BECC.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BECD.smi -OutFile BE/BECD.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEEA.smi -OutFile BE/BEEA.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEEB.smi -OutFile BE/BEEB.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEEC.smi -OutFile BE/BEEC.smi
New-Item -path BE -type directory; Invoke-WebRequest http://files.docking.org/2D/BE/BEED.smi -OutFile BE/BEED.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFAA.smi -OutFile BF/BFAA.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFAB.smi -OutFile BF/BFAB.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFAC.smi -OutFile BF/BFAC.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFAD.smi -OutFile BF/BFAD.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFBA.smi -OutFile BF/BFBA.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFBB.smi -OutFile BF/BFBB.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFBC.smi -OutFile BF/BFBC.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFBD.smi -OutFile BF/BFBD.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFCA.smi -OutFile BF/BFCA.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFCB.smi -OutFile BF/BFCB.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFCC.smi -OutFile BF/BFCC.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFCD.smi -OutFile BF/BFCD.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFEA.smi -OutFile BF/BFEA.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFEB.smi -OutFile BF/BFEB.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFEC.smi -OutFile BF/BFEC.smi
New-Item -path BF -type directory; Invoke-WebRequest http://files.docking.org/2D/BF/BFED.smi -OutFile BF/BFED.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCA.smi -OutFile AG/AGCA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCB.smi -OutFile AG/AGCB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCC.smi -OutFile AG/AGCC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCD.smi -OutFile AG/AGCD.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGEA.smi -OutFile AG/AGEA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGEB.smi -OutFile AG/AGEB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGEC.smi -OutFile AG/AGEC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGED.smi -OutFile AG/AGED.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGAA.smi -OutFile BG/BGAA.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGAB.smi -OutFile BG/BGAB.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGAC.smi -OutFile BG/BGAC.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGAD.smi -OutFile BG/BGAD.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGBA.smi -OutFile BG/BGBA.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGBB.smi -OutFile BG/BGBB.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGBC.smi -OutFile BG/BGBC.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGBD.smi -OutFile BG/BGBD.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGCA.smi -OutFile BG/BGCA.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGCB.smi -OutFile BG/BGCB.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGCC.smi -OutFile BG/BGCC.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGCD.smi -OutFile BG/BGCD.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGEA.smi -OutFile BG/BGEA.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGEB.smi -OutFile BG/BGEB.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGEC.smi -OutFile BG/BGEC.smi
New-Item -path BG -type directory; Invoke-WebRequest http://files.docking.org/2D/BG/BGED.smi -OutFile BG/BGED.smi
