New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAA.smi -OutFile AA/AAAA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAB.smi -OutFile AA/AAAB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAC.smi -OutFile AA/AAAC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AAAD.smi -OutFile AA/AAAD.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABA.smi -OutFile AA/AABA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABB.smi -OutFile AA/AABB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABC.smi -OutFile AA/AABC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AABD.smi -OutFile AA/AABD.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACA.smi -OutFile AA/AACA.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACB.smi -OutFile AA/AACB.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACC.smi -OutFile AA/AACC.smi
New-Item -path AA -type directory; Invoke-WebRequest http://files.docking.org/2D/AA/AACD.smi -OutFile AA/AACD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAA.smi -OutFile AB/ABAA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAB.smi -OutFile AB/ABAB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAC.smi -OutFile AB/ABAC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABAD.smi -OutFile AB/ABAD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBA.smi -OutFile AB/ABBA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBB.smi -OutFile AB/ABBB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBC.smi -OutFile AB/ABBC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABBD.smi -OutFile AB/ABBD.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCA.smi -OutFile AB/ABCA.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCB.smi -OutFile AB/ABCB.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCC.smi -OutFile AB/ABCC.smi
New-Item -path AB -type directory; Invoke-WebRequest http://files.docking.org/2D/AB/ABCD.smi -OutFile AB/ABCD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAA.smi -OutFile AC/ACAA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAB.smi -OutFile AC/ACAB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAC.smi -OutFile AC/ACAC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACAD.smi -OutFile AC/ACAD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBA.smi -OutFile AC/ACBA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBB.smi -OutFile AC/ACBB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBC.smi -OutFile AC/ACBC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACBD.smi -OutFile AC/ACBD.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCA.smi -OutFile AC/ACCA.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCB.smi -OutFile AC/ACCB.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCC.smi -OutFile AC/ACCC.smi
New-Item -path AC -type directory; Invoke-WebRequest http://files.docking.org/2D/AC/ACCD.smi -OutFile AC/ACCD.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAA.smi -OutFile AD/ADAA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAB.smi -OutFile AD/ADAB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAC.smi -OutFile AD/ADAC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADAD.smi -OutFile AD/ADAD.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBA.smi -OutFile AD/ADBA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBB.smi -OutFile AD/ADBB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBC.smi -OutFile AD/ADBC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADBD.smi -OutFile AD/ADBD.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCA.smi -OutFile AD/ADCA.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCB.smi -OutFile AD/ADCB.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCC.smi -OutFile AD/ADCC.smi
New-Item -path AD -type directory; Invoke-WebRequest http://files.docking.org/2D/AD/ADCD.smi -OutFile AD/ADCD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAA.smi -OutFile AE/AEAA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAB.smi -OutFile AE/AEAB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAC.smi -OutFile AE/AEAC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEAD.smi -OutFile AE/AEAD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBA.smi -OutFile AE/AEBA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBB.smi -OutFile AE/AEBB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBC.smi -OutFile AE/AEBC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AEBD.smi -OutFile AE/AEBD.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECA.smi -OutFile AE/AECA.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECB.smi -OutFile AE/AECB.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECC.smi -OutFile AE/AECC.smi
New-Item -path AE -type directory; Invoke-WebRequest http://files.docking.org/2D/AE/AECD.smi -OutFile AE/AECD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAA.smi -OutFile AF/AFAA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAB.smi -OutFile AF/AFAB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAC.smi -OutFile AF/AFAC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFAD.smi -OutFile AF/AFAD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBA.smi -OutFile AF/AFBA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBB.smi -OutFile AF/AFBB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBC.smi -OutFile AF/AFBC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFBD.smi -OutFile AF/AFBD.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCA.smi -OutFile AF/AFCA.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCB.smi -OutFile AF/AFCB.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCC.smi -OutFile AF/AFCC.smi
New-Item -path AF -type directory; Invoke-WebRequest http://files.docking.org/2D/AF/AFCD.smi -OutFile AF/AFCD.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAA.smi -OutFile AG/AGAA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAB.smi -OutFile AG/AGAB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAC.smi -OutFile AG/AGAC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGAD.smi -OutFile AG/AGAD.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBA.smi -OutFile AG/AGBA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBB.smi -OutFile AG/AGBB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBC.smi -OutFile AG/AGBC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGBD.smi -OutFile AG/AGBD.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCA.smi -OutFile AG/AGCA.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCB.smi -OutFile AG/AGCB.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCC.smi -OutFile AG/AGCC.smi
New-Item -path AG -type directory; Invoke-WebRequest http://files.docking.org/2D/AG/AGCD.smi -OutFile AG/AGCD.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHAA.smi -OutFile AH/AHAA.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHAB.smi -OutFile AH/AHAB.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHAC.smi -OutFile AH/AHAC.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHAD.smi -OutFile AH/AHAD.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHBA.smi -OutFile AH/AHBA.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHBB.smi -OutFile AH/AHBB.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHBC.smi -OutFile AH/AHBC.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHCA.smi -OutFile AH/AHCA.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHCB.smi -OutFile AH/AHCB.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHCC.smi -OutFile AH/AHCC.smi
New-Item -path AH -type directory; Invoke-WebRequest http://files.docking.org/2D/AH/AHCD.smi -OutFile AH/AHCD.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIAA.smi -OutFile AI/AIAA.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIAB.smi -OutFile AI/AIAB.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIAC.smi -OutFile AI/AIAC.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIAD.smi -OutFile AI/AIAD.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIBA.smi -OutFile AI/AIBA.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIBB.smi -OutFile AI/AIBB.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIBC.smi -OutFile AI/AIBC.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AIBD.smi -OutFile AI/AIBD.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AICA.smi -OutFile AI/AICA.smi
New-Item -path AI -type directory; Invoke-WebRequest http://files.docking.org/2D/AI/AICB.smi -OutFile AI/AICB.smi
New-Item -path AJ -type directory; Invoke-WebRequest http://files.docking.org/2D/AJ/AJAA.smi -OutFile AJ/AJAA.smi
New-Item -path AJ -type directory; Invoke-WebRequest http://files.docking.org/2D/AJ/AJAB.smi -OutFile AJ/AJAB.smi
New-Item -path AJ -type directory; Invoke-WebRequest http://files.docking.org/2D/AJ/AJAC.smi -OutFile AJ/AJAC.smi
New-Item -path AJ -type directory; Invoke-WebRequest http://files.docking.org/2D/AJ/AJAD.smi -OutFile AJ/AJAD.smi
New-Item -path AK -type directory; Invoke-WebRequest http://files.docking.org/2D/AK/AKAA.smi -OutFile AK/AKAA.smi
New-Item -path AK -type directory; Invoke-WebRequest http://files.docking.org/2D/AK/AKAB.smi -OutFile AK/AKAB.smi
New-Item -path AK -type directory; Invoke-WebRequest http://files.docking.org/2D/AK/AKAC.smi -OutFile AK/AKAC.smi
